# Generated by Django 5.2.1 on 2025-05-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrowsinessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=30)),
                ('plate', models.CharField(max_length=20)),
                ('blink_count', models.IntegerField()),
                ('yawn_count', models.IntegerField()),
                ('nod_count', models.IntegerField()),
                ('critical_events', models.JSONField()),
                ('video_names', models.JSONField()),
                ('generated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
