# Generated by Django 5.2.1 on 2025-05-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drowsinessreport',
            name='estado',
            field=models.CharField(default='No revisado', max_length=20),
        ),
        migrations.AddField(
            model_name='drowsinessreport',
            name='gravedad',
            field=models.CharField(default='Desconocida', max_length=20),
        ),
        migrations.AlterField(
            model_name='drowsinessreport',
            name='dni',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='drowsinessreport',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='drowsinessreport',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='drowsinessreport',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='drowsinessreport',
            name='vehicle_type',
            field=models.CharField(max_length=100),
        ),
    ]
