# Generated by Django 5.2.1 on 2025-05-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_drowsinessreport_estado_drowsinessreport_gravedad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drowsinessreport',
            name='url_videos',
            field=models.JSONField(default=list),
        ),
    ]
