# Generated by Django 5.2.1 on 2025-06-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_drowsinessreport_url_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='drowsinessreport',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
